### PR TITLE
Current batch race fix

### LINKED ISSUE #130: WorkerManager's currentBatch map is susceptible to races
Running `go test` with the `-race` flag makes this clear:

```
go test -v -race -run 'TestWorkerManager' .
=== RUN TestWorkerManager
==================
WARNING: DATA RACE
Write by goroutine 14:
  runtime.mapdelete()
      /usr/local/go/src/runtime/hashmap.go:495 +0x0
  github.com/stealthly/go_kafka_client.(*WorkerManager).taskIsDone()
      /home/spencer/go/src/github.com/stealthly/go_kafka_client/workers.go:332 +0x162
  github.com/stealthly/go_kafka_client.(*WorkerManager).taskSucceeded()
      /home/spencer/go/src/github.com/stealthly/go_kafka_client/workers.go:326 +0x232
  github.com/stealthly/go_kafka_client.(*WorkerManager).processBatch()
      /home/spencer/go/src/github.com/stealthly/go_kafka_client/workers.go:242 +0x618

Previous read by goroutine 13:
  runtime.mapaccess1()
      /usr/local/go/src/runtime/hashmap.go:244 +0x0
  github.com/stealthly/go_kafka_client.func·043()
      /home/spencer/go/src/github.com/stealthly/go_kafka_client/workers.go:155 +0x7c6
  github.com/stealthly/go_kafka_client.inLock()
      /home/spencer/go/src/github.com/stealthly/go_kafka_client/utils.go:44 +0x5e
  github.com/stealthly/go_kafka_client.(*WorkerManager).startBatch()
      /home/spencer/go/src/github.com/stealthly/go_kafka_client/workers.go:168 +0xa3
  github.com/stealthly/go_kafka_client.func·040()
      /home/spencer/go/src/github.com/stealthly/go_kafka_client/workers.go:107 +0x71
  github.com/rcrowley/go-metrics.(*StandardTimer).Time()
      /home/spencer/go/src/github.com/rcrowley/go-metrics/timer.go:212 +0x51
  github.com/stealthly/go_kafka_client.(*WorkerManager).Start()
      /home/spencer/go/src/github.com/stealthly/go_kafka_client/workers.go:108 +0x559

Goroutine 14 (running) created at:
  github.com/stealthly/go_kafka_client.(*WorkerManager).Start()
      /home/spencer/go/src/github.com/stealthly/go_kafka_client/workers.go:92 +0x7f

Goroutine 13 (running) created at:
  github.com/stealthly/go_kafka_client.TestWorkerManager()
      /home/spencer/go/src/github.com/stealthly/go_kafka_client/workers_test.go:123 +0x365
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:447 +0x133
==================
--- PASS: TestWorkerManager (3.00s)
PASS
ok  	github.com/stealthly/go_kafka_client	3.010s
```

This race causes quick crashes in Go 1.5beta1. I'm not sure exactly why, but it seems like the new incremental garbage collector is unhappy with this map, which makes some sense.

### PR DESCRIPTION
**Pull request by spenczar**
Fixes #130.

I ran benchmarks on my laptop and found that performance is slightly degraded for TaskStrategies which process messages quickly (10μs and 100μs: +6% and +4% time per message, respectively), but the effect diminishes over a few hundred μs (-1% time per message for 1000μs). I didn't see any consistent effects based on message batch sizes or number of workers in the WorkerManager's pool.

I've verified that `go test -race -run 'TestWorkerManager'` doesn't throw race detection warnings anymore. Not sure yet if this resolves crashed in go1.5beta1.

### CODE REVIEW

File: workers.go [hunk 1]
```diff
@@ -313,13 +313,6 @@ func (wm *WorkerManager) triggerShutdownIfRequired(decision *FailedDecision) {
 	}
 }
 
-func (wm *WorkerManager) stopBatch() {
```
Comment (spenczar) [inline workers.go]: This function wasn't called anywhere, and it scared me a lot - resetting the `currentBatch` to an empty map on the fly with no locking seems really dangerous.

Comment (serejja) [inline workers.go]: This is related to #121 - the failure handling logic was broken and we just forgot to remove that `stopBatch`. Thanks for noticing

**Comment by serejja** [comment]
LGTM. @edgefox, can you also review that? Maybe you'll notice something I missed
